<?xml version="1.0" encoding="utf-8"?><Database Name="Dranken" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2HSIHH3\SQLEXPRESS;Initial Catalog=Dranken;Integrated Security=True" SettingsObjectName="Dranken.Properties.Settings" SettingsPropertyName="DrankenConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dranken" Member="drankens">
    <Type Name="dranken">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Soort" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prijs" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>